codescanning:
  level: error
  conditions:
    ids:
      - "java/sql-injection" 
dependabot:
  level: high

licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

secretscanning:
  level: all
